name: Update Traffic Graph

permissions:
  contents: write

on:
  schedule:
#    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout WorkFlowRepo (Free Repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install requests matplotlib

      - name: Fetch traffic from AscendAI (Paid Repo)
        env:
          PAT_GITHUB: ${{ secrets.PULL_STATIK_PAT }}
          REPO: statikfintechllc/AscendAI
        run: python ./docs/graph/fetch_traffic.py

      - name: Commit & push graph changes (Free Repo)
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          git config --global user.name "gremlin-bot"
          git config --global user.email "actions@github.com"
          git add docs/graph/
          git commit -m "Update traffic data and graph" || echo "No changes to commit"
          git push
